language: ruby
rvm:
  - 2.2.3
env:
  global:
    - APP_NAME='Wrocław RoR Workshops'
    - RAILS_ENV=test
services:
  - postgresql
script:
  - bundle exec rake db:schema:load --trace
  - bundle exec rspec
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database workshops_test;' -U postgres
  -
addons:
  postgresql: '9.3'
